### ISSUE TITLE
feemarket: non-determinism on block gas

### ISSUE THREAD

**Issue by mmsqe** [evmos/ethermint#1151]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. run `make test-sim-nondeterminism` with https://github.com/mmsqe/ethermint/commit/4d64b4b4f74ff025c5399aa1a6e142c13fd514c3

__Expected behavior:__ [```--- PASS: TestAppStateDeterminism```]

__Actual behavior:__ [```--- FAIL: TestAppStateDeterminism ```]

__Additional info: [block_gas](https://github.com/evmos/ethermint/blob/a8d3805ddf27d37fd962ba2f8294de82ea4f637e/x/feemarket/keeper/abci.go#L47) brings the diff caused by random length [memo](https://github.com/mmsqe/cosmos-sdk/commit/dbe1dba5a6dfa118412a6a3ea795c5f1b746eee7), fixed memo length could [bypass](https://github.com/mmsqe/ethermint/commit/a0d61a1e3d922214e09c07896f9193f466dca640) the test

**Comment by Muggle-Du** [comment]
the reason is easy:
https://github.com/mmsqe/cosmos-sdk/blob/dbe1dba5a6dfa118412a6a3ea795c5f1b746eee7/simapp/helpers/test_helpers.go#L26
```go
r := rand.New(rand.NewSource(time.Now().UnixNano()))
```
`GenTx` is not using `Simstate.Rand`, so every time it creates memo with different length.
And `ethermint.AnteHandler` is consuming gas according to the tx bytes length, so finally gas used is not deterministic.

**Comment by mmsqe** [comment]
[memo](https://github.com/mmsqe/cosmos-sdk/commit/aef88ebbde6256e5f49f1efe7ebc2c69541aa6e4) with rand seed works, this test "PASS" randomly before with larger NumBlocks, since we get [blockSize](https://github.com/cosmos/cosmos-sdk/blob/main/x/simulation/util.go#L36) 0 with gasWanted 0 based on matrix, which always compare same hash
